language: rust
rust:
    - stable
    - beta
    - nightly
notifications:
    email:
        - mitchell.nordine@gmail.com
os:
    - linux
before_script:
    - rustc --version
    - cargo --version
script:
    - cargo build -v
    - cargo test -v
    - cargo test --features="serde_serialization" -v
    - cargo doc -v
